pmid file path: 'notebooks/data/test_pmid_list.csv'
biocjson output path: biocjson
max_tokens: 300
transformer_model: 'microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext' #'sentence-transformers/all-mpnet-base-v2'
db name: '/users/anglup/github/pubmed-rag/demo.db'
tsne: 'tsne.png' #or empty string or False if no tsne wanted
n_results: 10
output_dimensions: 768